FROM node:22-slim

WORKDIR /app

COPY package.json package-lock.json ./
COPY domain/package*.json ./domain/
COPY apps/frontend/package*.json ./apps/frontend/

RUN npm install

COPY ./ ./

RUN npx tsc --project ./domain/tsconfig.json
RUN npx tsc --project ./apps/frontend/tsconfig.json

EXPOSE 5173

CMD ["npm", "run", "dev", "--prefix", "./apps/frontend", "--", "--host", "0.0.0.0", "--port", "5173" ]